### ISSUE TITLE
Søge felt

### ISSUE THREAD

**Issue by Dani144c** [org-LEHD/go-easy-mobile#3]
**Titel:** 
Forbedret søgefunktionalitet med dynamisk opdatering af søgeresultater

**Beskrivelse:**
Som en bruger, ønsker jeg at kunne foretage søgninger på annoncører og seværdigheder ved at indtaste søgeord i søgefeltet på skærmen. Jeg forventer, at søgeresultaterne præsenteres på en korre
kt og dynamisk måde baseret på det indtastede søgeord.

**Acceptkriterier:**

Aktøren kan indtaste et søgeord i søgefeltet.
Når aktøren begynder at skrive i søgefeltet, opdateres søgeresultaterne dynamisk for at matche det indtastede søgeord.
Søgeresultaterne viser en liste af annoncører og seværdigheder, der er relevante i forhold til det indtastede søgeord.
Relevante resultater præsenteres øverst i søgeresultatlisten.
Søgeresultater, der matcher det indtastede søgeord, markeres tydeligt med fed skrift, så aktøren kan identificere, hvorfor et resultat blev vist.
Hvis der ikke er nogen matchende resultater, præsenteres en tom liste med passende feedback til brugeren.

![unnamed](https://github.com/org-LEHD/go-easy-mobile/assets/48748241/13a73d38-bb68-4ce1-82db-e6ece692cd38)

**Comment by hengre** [comment]
I første omgang skal vi koncentrere os om annoncørerne og vente med seværdighederne til / hvis der er tid
